/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContributeRouteImport } from './routes/contribute'
import { Route as DraftRouteImport } from './routes/draft'
import { Route as GuestsRouteImport } from './routes/guests'
import { Route as SiteDotwebmanifestRouteImport } from './routes/site[.]webmanifest'
import { Route as ContributeIndexRouteImport } from './routes/contribute.index'
import { Route as ContributeLinkIdRouteImport } from './routes/contribute.$linkId'
import { Route as DraftIndexRouteImport } from './routes/draft.index'
import { Route as DraftLinkIdRouteImport } from './routes/draft.$linkId'
import { Route as IPublicIdRouteImport } from './routes/i.$publicId'
import { Route as ShareShareIdRouteImport } from './routes/share.$shareId'
import { Route as ApiV1ExtrasRouteImport } from './routes/api/v1/extras'
import { Route as ApiV1GuestsRouteImport } from './routes/api/v1/guests'
import { Route as ApiV1InterviewsRouteImport } from './routes/api/v1/interviews'
import { Route as ApiV1LatestRouteImport } from './routes/api/v1/latest'
import { Route as ShareShareIdPortraitRouteImport } from './routes/share.$shareId.portrait'
import { Route as ApiV1AdminDraftsRouteImport } from './routes/api/v1/admin.drafts'
import { Route as ApiV1AdminGuestsRouteImport } from './routes/api/v1/admin.guests'
import { Route as ApiV1AdminInterviewsRouteImport } from './routes/api/v1/admin.interviews'
import { Route as ApiV1AdminPublishRouteImport } from './routes/api/v1/admin.publish'
import { Route as ApiV1AdminShareSnapshotsRouteImport } from './routes/api/v1/admin.share-snapshots'
import { Route as ApiV1GuestsGuestIdRouteImport } from './routes/api/v1/guests.$guestId'
import { Route as ApiV1InterviewsPublicIdRouteImport } from './routes/api/v1/interviews.$publicId'
import { Route as ApiV1AdminInterviewsInterviewIdRouteImport } from './routes/api/v1/admin.interviews.$interviewId'
import { Route as ApiV1AdminShareSnapshotsSnapshotIdRouteImport } from './routes/api/v1/admin.share-snapshots.$snapshotId'
import { Route as ApiV1ContributionLinkIdPortraitImageRouteImport } from './routes/api/v1/contribution.$linkId.portrait-image'
import { Route as ApiV1ContributionLinkIdTranscribeRouteImport } from './routes/api/v1/contribution.$linkId.transcribe'
import { Route as ApiV1InterviewsPublicIdPortraitRouteImport } from './routes/api/v1/interviews.$publicId.portrait'
import { Route as ApiV1AdminInterviewsInterviewIdGuestRouteImport } from './routes/api/v1/admin.interviews.$interviewId.guest'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributeRoute = ContributeRouteImport.update({
  id: '/contribute',
  path: '/contribute',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftRoute = DraftRouteImport.update({
  id: '/draft',
  path: '/draft',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestsRoute = GuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteDotwebmanifestRoute = SiteDotwebmanifestRouteImport.update({
  id: '/site.webmanifest',
  path: '/site.webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributeIndexRoute = ContributeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContributeRoute,
} as any)
const ContributeLinkIdRoute = ContributeLinkIdRouteImport.update({
  id: '/$linkId',
  path: '/$linkId',
  getParentRoute: () => ContributeRoute,
} as any)
const DraftIndexRoute = DraftIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DraftRoute,
} as any)
const DraftLinkIdRoute = DraftLinkIdRouteImport.update({
  id: '/$linkId',
  path: '/$linkId',
  getParentRoute: () => DraftRoute,
} as any)
const IPublicIdRoute = IPublicIdRouteImport.update({
  id: '/i/$publicId',
  path: '/i/$publicId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareShareIdRoute = ShareShareIdRouteImport.update({
  id: '/share/$shareId',
  path: '/share/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ExtrasRoute = ApiV1ExtrasRouteImport.update({
  id: '/api/v1/extras',
  path: '/api/v1/extras',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1GuestsRoute = ApiV1GuestsRouteImport.update({
  id: '/api/v1/guests',
  path: '/api/v1/guests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1InterviewsRoute = ApiV1InterviewsRouteImport.update({
  id: '/api/v1/interviews',
  path: '/api/v1/interviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1LatestRoute = ApiV1LatestRouteImport.update({
  id: '/api/v1/latest',
  path: '/api/v1/latest',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareShareIdPortraitRoute = ShareShareIdPortraitRouteImport.update({
  id: '/portrait',
  path: '/portrait',
  getParentRoute: () => ShareShareIdRoute,
} as any)
const ApiV1AdminDraftsRoute = ApiV1AdminDraftsRouteImport.update({
  id: '/api/v1/admin/drafts',
  path: '/api/v1/admin/drafts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AdminGuestsRoute = ApiV1AdminGuestsRouteImport.update({
  id: '/api/v1/admin/guests',
  path: '/api/v1/admin/guests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AdminInterviewsRoute = ApiV1AdminInterviewsRouteImport.update({
  id: '/api/v1/admin/interviews',
  path: '/api/v1/admin/interviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AdminPublishRoute = ApiV1AdminPublishRouteImport.update({
  id: '/api/v1/admin/publish',
  path: '/api/v1/admin/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AdminShareSnapshotsRoute =
  ApiV1AdminShareSnapshotsRouteImport.update({
    id: '/api/v1/admin/share-snapshots',
    path: '/api/v1/admin/share-snapshots',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1GuestsGuestIdRoute = ApiV1GuestsGuestIdRouteImport.update({
  id: '/$guestId',
  path: '/$guestId',
  getParentRoute: () => ApiV1GuestsRoute,
} as any)
const ApiV1InterviewsPublicIdRoute = ApiV1InterviewsPublicIdRouteImport.update({
  id: '/$publicId',
  path: '/$publicId',
  getParentRoute: () => ApiV1InterviewsRoute,
} as any)
const ApiV1AdminInterviewsInterviewIdRoute =
  ApiV1AdminInterviewsInterviewIdRouteImport.update({
    id: '/$interviewId',
    path: '/$interviewId',
    getParentRoute: () => ApiV1AdminInterviewsRoute,
  } as any)
const ApiV1AdminShareSnapshotsSnapshotIdRoute =
  ApiV1AdminShareSnapshotsSnapshotIdRouteImport.update({
    id: '/$snapshotId',
    path: '/$snapshotId',
    getParentRoute: () => ApiV1AdminShareSnapshotsRoute,
  } as any)
const ApiV1ContributionLinkIdPortraitImageRoute =
  ApiV1ContributionLinkIdPortraitImageRouteImport.update({
    id: '/api/v1/contribution/$linkId/portrait-image',
    path: '/api/v1/contribution/$linkId/portrait-image',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1ContributionLinkIdTranscribeRoute =
  ApiV1ContributionLinkIdTranscribeRouteImport.update({
    id: '/api/v1/contribution/$linkId/transcribe',
    path: '/api/v1/contribution/$linkId/transcribe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1InterviewsPublicIdPortraitRoute =
  ApiV1InterviewsPublicIdPortraitRouteImport.update({
    id: '/portrait',
    path: '/portrait',
    getParentRoute: () => ApiV1InterviewsPublicIdRoute,
  } as any)
const ApiV1AdminInterviewsInterviewIdGuestRoute =
  ApiV1AdminInterviewsInterviewIdGuestRouteImport.update({
    id: '/guest',
    path: '/guest',
    getParentRoute: () => ApiV1AdminInterviewsInterviewIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contribute': typeof ContributeRouteWithChildren
  '/draft': typeof DraftRouteWithChildren
  '/guests': typeof GuestsRoute
  '/site.webmanifest': typeof SiteDotwebmanifestRoute
  '/contribute/$linkId': typeof ContributeLinkIdRoute
  '/draft/$linkId': typeof DraftLinkIdRoute
  '/i/$publicId': typeof IPublicIdRoute
  '/share/$shareId': typeof ShareShareIdRouteWithChildren
  '/contribute/': typeof ContributeIndexRoute
  '/draft/': typeof DraftIndexRoute
  '/api/v1/extras': typeof ApiV1ExtrasRoute
  '/api/v1/guests': typeof ApiV1GuestsRouteWithChildren
  '/api/v1/interviews': typeof ApiV1InterviewsRouteWithChildren
  '/api/v1/latest': typeof ApiV1LatestRoute
  '/share/$shareId/portrait': typeof ShareShareIdPortraitRoute
  '/api/v1/admin/drafts': typeof ApiV1AdminDraftsRoute
  '/api/v1/admin/guests': typeof ApiV1AdminGuestsRoute
  '/api/v1/admin/interviews': typeof ApiV1AdminInterviewsRouteWithChildren
  '/api/v1/admin/publish': typeof ApiV1AdminPublishRoute
  '/api/v1/admin/share-snapshots': typeof ApiV1AdminShareSnapshotsRouteWithChildren
  '/api/v1/guests/$guestId': typeof ApiV1GuestsGuestIdRoute
  '/api/v1/interviews/$publicId': typeof ApiV1InterviewsPublicIdRouteWithChildren
  '/api/v1/admin/interviews/$interviewId': typeof ApiV1AdminInterviewsInterviewIdRouteWithChildren
  '/api/v1/admin/share-snapshots/$snapshotId': typeof ApiV1AdminShareSnapshotsSnapshotIdRoute
  '/api/v1/contribution/$linkId/portrait-image': typeof ApiV1ContributionLinkIdPortraitImageRoute
  '/api/v1/contribution/$linkId/transcribe': typeof ApiV1ContributionLinkIdTranscribeRoute
  '/api/v1/interviews/$publicId/portrait': typeof ApiV1InterviewsPublicIdPortraitRoute
  '/api/v1/admin/interviews/$interviewId/guest': typeof ApiV1AdminInterviewsInterviewIdGuestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guests': typeof GuestsRoute
  '/site.webmanifest': typeof SiteDotwebmanifestRoute
  '/contribute/$linkId': typeof ContributeLinkIdRoute
  '/draft/$linkId': typeof DraftLinkIdRoute
  '/i/$publicId': typeof IPublicIdRoute
  '/share/$shareId': typeof ShareShareIdRouteWithChildren
  '/contribute': typeof ContributeIndexRoute
  '/draft': typeof DraftIndexRoute
  '/api/v1/extras': typeof ApiV1ExtrasRoute
  '/api/v1/guests': typeof ApiV1GuestsRouteWithChildren
  '/api/v1/interviews': typeof ApiV1InterviewsRouteWithChildren
  '/api/v1/latest': typeof ApiV1LatestRoute
  '/share/$shareId/portrait': typeof ShareShareIdPortraitRoute
  '/api/v1/admin/drafts': typeof ApiV1AdminDraftsRoute
  '/api/v1/admin/guests': typeof ApiV1AdminGuestsRoute
  '/api/v1/admin/interviews': typeof ApiV1AdminInterviewsRouteWithChildren
  '/api/v1/admin/publish': typeof ApiV1AdminPublishRoute
  '/api/v1/admin/share-snapshots': typeof ApiV1AdminShareSnapshotsRouteWithChildren
  '/api/v1/guests/$guestId': typeof ApiV1GuestsGuestIdRoute
  '/api/v1/interviews/$publicId': typeof ApiV1InterviewsPublicIdRouteWithChildren
  '/api/v1/admin/interviews/$interviewId': typeof ApiV1AdminInterviewsInterviewIdRouteWithChildren
  '/api/v1/admin/share-snapshots/$snapshotId': typeof ApiV1AdminShareSnapshotsSnapshotIdRoute
  '/api/v1/contribution/$linkId/portrait-image': typeof ApiV1ContributionLinkIdPortraitImageRoute
  '/api/v1/contribution/$linkId/transcribe': typeof ApiV1ContributionLinkIdTranscribeRoute
  '/api/v1/interviews/$publicId/portrait': typeof ApiV1InterviewsPublicIdPortraitRoute
  '/api/v1/admin/interviews/$interviewId/guest': typeof ApiV1AdminInterviewsInterviewIdGuestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contribute': typeof ContributeRouteWithChildren
  '/draft': typeof DraftRouteWithChildren
  '/guests': typeof GuestsRoute
  '/site.webmanifest': typeof SiteDotwebmanifestRoute
  '/contribute/$linkId': typeof ContributeLinkIdRoute
  '/draft/$linkId': typeof DraftLinkIdRoute
  '/i/$publicId': typeof IPublicIdRoute
  '/share/$shareId': typeof ShareShareIdRouteWithChildren
  '/contribute/': typeof ContributeIndexRoute
  '/draft/': typeof DraftIndexRoute
  '/api/v1/extras': typeof ApiV1ExtrasRoute
  '/api/v1/guests': typeof ApiV1GuestsRouteWithChildren
  '/api/v1/interviews': typeof ApiV1InterviewsRouteWithChildren
  '/api/v1/latest': typeof ApiV1LatestRoute
  '/share/$shareId/portrait': typeof ShareShareIdPortraitRoute
  '/api/v1/admin/drafts': typeof ApiV1AdminDraftsRoute
  '/api/v1/admin/guests': typeof ApiV1AdminGuestsRoute
  '/api/v1/admin/interviews': typeof ApiV1AdminInterviewsRouteWithChildren
  '/api/v1/admin/publish': typeof ApiV1AdminPublishRoute
  '/api/v1/admin/share-snapshots': typeof ApiV1AdminShareSnapshotsRouteWithChildren
  '/api/v1/guests/$guestId': typeof ApiV1GuestsGuestIdRoute
  '/api/v1/interviews/$publicId': typeof ApiV1InterviewsPublicIdRouteWithChildren
  '/api/v1/admin/interviews/$interviewId': typeof ApiV1AdminInterviewsInterviewIdRouteWithChildren
  '/api/v1/admin/share-snapshots/$snapshotId': typeof ApiV1AdminShareSnapshotsSnapshotIdRoute
  '/api/v1/contribution/$linkId/portrait-image': typeof ApiV1ContributionLinkIdPortraitImageRoute
  '/api/v1/contribution/$linkId/transcribe': typeof ApiV1ContributionLinkIdTranscribeRoute
  '/api/v1/interviews/$publicId/portrait': typeof ApiV1InterviewsPublicIdPortraitRoute
  '/api/v1/admin/interviews/$interviewId/guest': typeof ApiV1AdminInterviewsInterviewIdGuestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contribute'
    | '/draft'
    | '/guests'
    | '/site.webmanifest'
    | '/contribute/$linkId'
    | '/draft/$linkId'
    | '/i/$publicId'
    | '/share/$shareId'
    | '/contribute/'
    | '/draft/'
    | '/api/v1/extras'
    | '/api/v1/guests'
    | '/api/v1/interviews'
    | '/api/v1/latest'
    | '/share/$shareId/portrait'
    | '/api/v1/admin/drafts'
    | '/api/v1/admin/guests'
    | '/api/v1/admin/interviews'
    | '/api/v1/admin/publish'
    | '/api/v1/admin/share-snapshots'
    | '/api/v1/guests/$guestId'
    | '/api/v1/interviews/$publicId'
    | '/api/v1/admin/interviews/$interviewId'
    | '/api/v1/admin/share-snapshots/$snapshotId'
    | '/api/v1/contribution/$linkId/portrait-image'
    | '/api/v1/contribution/$linkId/transcribe'
    | '/api/v1/interviews/$publicId/portrait'
    | '/api/v1/admin/interviews/$interviewId/guest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/guests'
    | '/site.webmanifest'
    | '/contribute/$linkId'
    | '/draft/$linkId'
    | '/i/$publicId'
    | '/share/$shareId'
    | '/contribute'
    | '/draft'
    | '/api/v1/extras'
    | '/api/v1/guests'
    | '/api/v1/interviews'
    | '/api/v1/latest'
    | '/share/$shareId/portrait'
    | '/api/v1/admin/drafts'
    | '/api/v1/admin/guests'
    | '/api/v1/admin/interviews'
    | '/api/v1/admin/publish'
    | '/api/v1/admin/share-snapshots'
    | '/api/v1/guests/$guestId'
    | '/api/v1/interviews/$publicId'
    | '/api/v1/admin/interviews/$interviewId'
    | '/api/v1/admin/share-snapshots/$snapshotId'
    | '/api/v1/contribution/$linkId/portrait-image'
    | '/api/v1/contribution/$linkId/transcribe'
    | '/api/v1/interviews/$publicId/portrait'
    | '/api/v1/admin/interviews/$interviewId/guest'
  id:
    | '__root__'
    | '/'
    | '/contribute'
    | '/draft'
    | '/guests'
    | '/site.webmanifest'
    | '/contribute/$linkId'
    | '/draft/$linkId'
    | '/i/$publicId'
    | '/share/$shareId'
    | '/contribute/'
    | '/draft/'
    | '/api/v1/extras'
    | '/api/v1/guests'
    | '/api/v1/interviews'
    | '/api/v1/latest'
    | '/share/$shareId/portrait'
    | '/api/v1/admin/drafts'
    | '/api/v1/admin/guests'
    | '/api/v1/admin/interviews'
    | '/api/v1/admin/publish'
    | '/api/v1/admin/share-snapshots'
    | '/api/v1/guests/$guestId'
    | '/api/v1/interviews/$publicId'
    | '/api/v1/admin/interviews/$interviewId'
    | '/api/v1/admin/share-snapshots/$snapshotId'
    | '/api/v1/contribution/$linkId/portrait-image'
    | '/api/v1/contribution/$linkId/transcribe'
    | '/api/v1/interviews/$publicId/portrait'
    | '/api/v1/admin/interviews/$interviewId/guest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContributeRoute: typeof ContributeRouteWithChildren
  DraftRoute: typeof DraftRouteWithChildren
  GuestsRoute: typeof GuestsRoute
  SiteDotwebmanifestRoute: typeof SiteDotwebmanifestRoute
  IPublicIdRoute: typeof IPublicIdRoute
  ShareShareIdRoute: typeof ShareShareIdRouteWithChildren
  ApiV1ExtrasRoute: typeof ApiV1ExtrasRoute
  ApiV1GuestsRoute: typeof ApiV1GuestsRouteWithChildren
  ApiV1InterviewsRoute: typeof ApiV1InterviewsRouteWithChildren
  ApiV1LatestRoute: typeof ApiV1LatestRoute
  ApiV1AdminDraftsRoute: typeof ApiV1AdminDraftsRoute
  ApiV1AdminGuestsRoute: typeof ApiV1AdminGuestsRoute
  ApiV1AdminInterviewsRoute: typeof ApiV1AdminInterviewsRouteWithChildren
  ApiV1AdminPublishRoute: typeof ApiV1AdminPublishRoute
  ApiV1AdminShareSnapshotsRoute: typeof ApiV1AdminShareSnapshotsRouteWithChildren
  ApiV1ContributionLinkIdPortraitImageRoute: typeof ApiV1ContributionLinkIdPortraitImageRoute
  ApiV1ContributionLinkIdTranscribeRoute: typeof ApiV1ContributionLinkIdTranscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribute': {
      id: '/contribute'
      path: '/contribute'
      fullPath: '/contribute'
      preLoaderRoute: typeof ContributeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draft': {
      id: '/draft'
      path: '/draft'
      fullPath: '/draft'
      preLoaderRoute: typeof DraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guests': {
      id: '/guests'
      path: '/guests'
      fullPath: '/guests'
      preLoaderRoute: typeof GuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site.webmanifest': {
      id: '/site.webmanifest'
      path: '/site.webmanifest'
      fullPath: '/site.webmanifest'
      preLoaderRoute: typeof SiteDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribute/': {
      id: '/contribute/'
      path: '/'
      fullPath: '/contribute/'
      preLoaderRoute: typeof ContributeIndexRouteImport
      parentRoute: typeof ContributeRoute
    }
    '/contribute/$linkId': {
      id: '/contribute/$linkId'
      path: '/$linkId'
      fullPath: '/contribute/$linkId'
      preLoaderRoute: typeof ContributeLinkIdRouteImport
      parentRoute: typeof ContributeRoute
    }
    '/draft/': {
      id: '/draft/'
      path: '/'
      fullPath: '/draft/'
      preLoaderRoute: typeof DraftIndexRouteImport
      parentRoute: typeof DraftRoute
    }
    '/draft/$linkId': {
      id: '/draft/$linkId'
      path: '/$linkId'
      fullPath: '/draft/$linkId'
      preLoaderRoute: typeof DraftLinkIdRouteImport
      parentRoute: typeof DraftRoute
    }
    '/i/$publicId': {
      id: '/i/$publicId'
      path: '/i/$publicId'
      fullPath: '/i/$publicId'
      preLoaderRoute: typeof IPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$shareId': {
      id: '/share/$shareId'
      path: '/share/$shareId'
      fullPath: '/share/$shareId'
      preLoaderRoute: typeof ShareShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/extras': {
      id: '/api/v1/extras'
      path: '/api/v1/extras'
      fullPath: '/api/v1/extras'
      preLoaderRoute: typeof ApiV1ExtrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/guests': {
      id: '/api/v1/guests'
      path: '/api/v1/guests'
      fullPath: '/api/v1/guests'
      preLoaderRoute: typeof ApiV1GuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/interviews': {
      id: '/api/v1/interviews'
      path: '/api/v1/interviews'
      fullPath: '/api/v1/interviews'
      preLoaderRoute: typeof ApiV1InterviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/latest': {
      id: '/api/v1/latest'
      path: '/api/v1/latest'
      fullPath: '/api/v1/latest'
      preLoaderRoute: typeof ApiV1LatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$shareId/portrait': {
      id: '/share/$shareId/portrait'
      path: '/portrait'
      fullPath: '/share/$shareId/portrait'
      preLoaderRoute: typeof ShareShareIdPortraitRouteImport
      parentRoute: typeof ShareShareIdRoute
    }
    '/api/v1/admin/drafts': {
      id: '/api/v1/admin/drafts'
      path: '/api/v1/admin/drafts'
      fullPath: '/api/v1/admin/drafts'
      preLoaderRoute: typeof ApiV1AdminDraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/admin/guests': {
      id: '/api/v1/admin/guests'
      path: '/api/v1/admin/guests'
      fullPath: '/api/v1/admin/guests'
      preLoaderRoute: typeof ApiV1AdminGuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/admin/interviews': {
      id: '/api/v1/admin/interviews'
      path: '/api/v1/admin/interviews'
      fullPath: '/api/v1/admin/interviews'
      preLoaderRoute: typeof ApiV1AdminInterviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/admin/publish': {
      id: '/api/v1/admin/publish'
      path: '/api/v1/admin/publish'
      fullPath: '/api/v1/admin/publish'
      preLoaderRoute: typeof ApiV1AdminPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/admin/share-snapshots': {
      id: '/api/v1/admin/share-snapshots'
      path: '/api/v1/admin/share-snapshots'
      fullPath: '/api/v1/admin/share-snapshots'
      preLoaderRoute: typeof ApiV1AdminShareSnapshotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/guests/$guestId': {
      id: '/api/v1/guests/$guestId'
      path: '/$guestId'
      fullPath: '/api/v1/guests/$guestId'
      preLoaderRoute: typeof ApiV1GuestsGuestIdRouteImport
      parentRoute: typeof ApiV1GuestsRoute
    }
    '/api/v1/interviews/$publicId': {
      id: '/api/v1/interviews/$publicId'
      path: '/$publicId'
      fullPath: '/api/v1/interviews/$publicId'
      preLoaderRoute: typeof ApiV1InterviewsPublicIdRouteImport
      parentRoute: typeof ApiV1InterviewsRoute
    }
    '/api/v1/admin/interviews/$interviewId': {
      id: '/api/v1/admin/interviews/$interviewId'
      path: '/$interviewId'
      fullPath: '/api/v1/admin/interviews/$interviewId'
      preLoaderRoute: typeof ApiV1AdminInterviewsInterviewIdRouteImport
      parentRoute: typeof ApiV1AdminInterviewsRoute
    }
    '/api/v1/admin/share-snapshots/$snapshotId': {
      id: '/api/v1/admin/share-snapshots/$snapshotId'
      path: '/$snapshotId'
      fullPath: '/api/v1/admin/share-snapshots/$snapshotId'
      preLoaderRoute: typeof ApiV1AdminShareSnapshotsSnapshotIdRouteImport
      parentRoute: typeof ApiV1AdminShareSnapshotsRoute
    }
    '/api/v1/contribution/$linkId/portrait-image': {
      id: '/api/v1/contribution/$linkId/portrait-image'
      path: '/api/v1/contribution/$linkId/portrait-image'
      fullPath: '/api/v1/contribution/$linkId/portrait-image'
      preLoaderRoute: typeof ApiV1ContributionLinkIdPortraitImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/contribution/$linkId/transcribe': {
      id: '/api/v1/contribution/$linkId/transcribe'
      path: '/api/v1/contribution/$linkId/transcribe'
      fullPath: '/api/v1/contribution/$linkId/transcribe'
      preLoaderRoute: typeof ApiV1ContributionLinkIdTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/interviews/$publicId/portrait': {
      id: '/api/v1/interviews/$publicId/portrait'
      path: '/portrait'
      fullPath: '/api/v1/interviews/$publicId/portrait'
      preLoaderRoute: typeof ApiV1InterviewsPublicIdPortraitRouteImport
      parentRoute: typeof ApiV1InterviewsPublicIdRoute
    }
    '/api/v1/admin/interviews/$interviewId/guest': {
      id: '/api/v1/admin/interviews/$interviewId/guest'
      path: '/guest'
      fullPath: '/api/v1/admin/interviews/$interviewId/guest'
      preLoaderRoute: typeof ApiV1AdminInterviewsInterviewIdGuestRouteImport
      parentRoute: typeof ApiV1AdminInterviewsInterviewIdRoute
    }
  }
}

interface ContributeRouteChildren {
  ContributeLinkIdRoute: typeof ContributeLinkIdRoute
  ContributeIndexRoute: typeof ContributeIndexRoute
}

const ContributeRouteChildren: ContributeRouteChildren = {
  ContributeLinkIdRoute: ContributeLinkIdRoute,
  ContributeIndexRoute: ContributeIndexRoute,
}

const ContributeRouteWithChildren = ContributeRoute._addFileChildren(
  ContributeRouteChildren,
)

interface DraftRouteChildren {
  DraftLinkIdRoute: typeof DraftLinkIdRoute
  DraftIndexRoute: typeof DraftIndexRoute
}

const DraftRouteChildren: DraftRouteChildren = {
  DraftLinkIdRoute: DraftLinkIdRoute,
  DraftIndexRoute: DraftIndexRoute,
}

const DraftRouteWithChildren = DraftRoute._addFileChildren(DraftRouteChildren)

interface ShareShareIdRouteChildren {
  ShareShareIdPortraitRoute: typeof ShareShareIdPortraitRoute
}

const ShareShareIdRouteChildren: ShareShareIdRouteChildren = {
  ShareShareIdPortraitRoute: ShareShareIdPortraitRoute,
}

const ShareShareIdRouteWithChildren = ShareShareIdRoute._addFileChildren(
  ShareShareIdRouteChildren,
)

interface ApiV1GuestsRouteChildren {
  ApiV1GuestsGuestIdRoute: typeof ApiV1GuestsGuestIdRoute
}

const ApiV1GuestsRouteChildren: ApiV1GuestsRouteChildren = {
  ApiV1GuestsGuestIdRoute: ApiV1GuestsGuestIdRoute,
}

const ApiV1GuestsRouteWithChildren = ApiV1GuestsRoute._addFileChildren(
  ApiV1GuestsRouteChildren,
)

interface ApiV1InterviewsPublicIdRouteChildren {
  ApiV1InterviewsPublicIdPortraitRoute: typeof ApiV1InterviewsPublicIdPortraitRoute
}

const ApiV1InterviewsPublicIdRouteChildren: ApiV1InterviewsPublicIdRouteChildren =
  {
    ApiV1InterviewsPublicIdPortraitRoute: ApiV1InterviewsPublicIdPortraitRoute,
  }

const ApiV1InterviewsPublicIdRouteWithChildren =
  ApiV1InterviewsPublicIdRoute._addFileChildren(
    ApiV1InterviewsPublicIdRouteChildren,
  )

interface ApiV1InterviewsRouteChildren {
  ApiV1InterviewsPublicIdRoute: typeof ApiV1InterviewsPublicIdRouteWithChildren
}

const ApiV1InterviewsRouteChildren: ApiV1InterviewsRouteChildren = {
  ApiV1InterviewsPublicIdRoute: ApiV1InterviewsPublicIdRouteWithChildren,
}

const ApiV1InterviewsRouteWithChildren = ApiV1InterviewsRoute._addFileChildren(
  ApiV1InterviewsRouteChildren,
)

interface ApiV1AdminInterviewsInterviewIdRouteChildren {
  ApiV1AdminInterviewsInterviewIdGuestRoute: typeof ApiV1AdminInterviewsInterviewIdGuestRoute
}

const ApiV1AdminInterviewsInterviewIdRouteChildren: ApiV1AdminInterviewsInterviewIdRouteChildren =
  {
    ApiV1AdminInterviewsInterviewIdGuestRoute:
      ApiV1AdminInterviewsInterviewIdGuestRoute,
  }

const ApiV1AdminInterviewsInterviewIdRouteWithChildren =
  ApiV1AdminInterviewsInterviewIdRoute._addFileChildren(
    ApiV1AdminInterviewsInterviewIdRouteChildren,
  )

interface ApiV1AdminInterviewsRouteChildren {
  ApiV1AdminInterviewsInterviewIdRoute: typeof ApiV1AdminInterviewsInterviewIdRouteWithChildren
}

const ApiV1AdminInterviewsRouteChildren: ApiV1AdminInterviewsRouteChildren = {
  ApiV1AdminInterviewsInterviewIdRoute:
    ApiV1AdminInterviewsInterviewIdRouteWithChildren,
}

const ApiV1AdminInterviewsRouteWithChildren =
  ApiV1AdminInterviewsRoute._addFileChildren(ApiV1AdminInterviewsRouteChildren)

interface ApiV1AdminShareSnapshotsRouteChildren {
  ApiV1AdminShareSnapshotsSnapshotIdRoute: typeof ApiV1AdminShareSnapshotsSnapshotIdRoute
}

const ApiV1AdminShareSnapshotsRouteChildren: ApiV1AdminShareSnapshotsRouteChildren =
  {
    ApiV1AdminShareSnapshotsSnapshotIdRoute:
      ApiV1AdminShareSnapshotsSnapshotIdRoute,
  }

const ApiV1AdminShareSnapshotsRouteWithChildren =
  ApiV1AdminShareSnapshotsRoute._addFileChildren(
    ApiV1AdminShareSnapshotsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContributeRoute: ContributeRouteWithChildren,
  DraftRoute: DraftRouteWithChildren,
  GuestsRoute: GuestsRoute,
  SiteDotwebmanifestRoute: SiteDotwebmanifestRoute,
  IPublicIdRoute: IPublicIdRoute,
  ShareShareIdRoute: ShareShareIdRouteWithChildren,
  ApiV1ExtrasRoute: ApiV1ExtrasRoute,
  ApiV1GuestsRoute: ApiV1GuestsRouteWithChildren,
  ApiV1InterviewsRoute: ApiV1InterviewsRouteWithChildren,
  ApiV1LatestRoute: ApiV1LatestRoute,
  ApiV1AdminDraftsRoute: ApiV1AdminDraftsRoute,
  ApiV1AdminGuestsRoute: ApiV1AdminGuestsRoute,
  ApiV1AdminInterviewsRoute: ApiV1AdminInterviewsRouteWithChildren,
  ApiV1AdminPublishRoute: ApiV1AdminPublishRoute,
  ApiV1AdminShareSnapshotsRoute: ApiV1AdminShareSnapshotsRouteWithChildren,
  ApiV1ContributionLinkIdPortraitImageRoute:
    ApiV1ContributionLinkIdPortraitImageRoute,
  ApiV1ContributionLinkIdTranscribeRoute:
    ApiV1ContributionLinkIdTranscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
